webapp:
  image: qftgtr/yeoman
  container_name: webapp
  volumes:
    - $PWD/webapp:/home/yeoman/webapp
  working_dir: /home/yeoman/webapp
  expose:
    - "3001"
    - "9000"
  ports:
    - "3001:3001"
    - "9000:9000"
  command: gulp serve